uploads = []

[[generated]]
id = "BSiX1bkCUMo0Lw7GCWyZz"
uri = "file://artifacts/my-vault/assets/images/icon.png"
type = "image"
title = "my vault app icon"

[[outputs]]
id = "8KnfARI12duTFHX8ARTCP"
uri = "file://RUN_LOCALLY.md"
type = "text"
title = "RUN_LOCALLY.md"

[[outputs]]
id = "6udyRx6Vjsh85gmyveVgT"
uri = "file://RUN_ON_CLOUD.md"
type = "text"
title = "RUN_ON_CLOUD.md"

[[outputs]]
id = "nGV4aK-FUBNbKGohojZdS"
uri = "file://MY_VAULT.md"
type = "text"
title = "MY_VAULT.md"
